# Generated by Django 2.2.16 on 2021-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Details',
            new_name='Insert',
        ),
    ]
